config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#home'
  get 'about', to: 'application#about'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#fb_create'
  
  get 'contact', to: 'contacts#new', as: 'contact_page'
  get 'most-active-user', to: 'users#most_active_user'

  resources :users do
    get :admins, on: :collection
  	resources :transactions
    resources :events, only: [:index, :show] do
      resources :transactions, only: [:index]
    end
  end
  resources :contacts, only: [:new, :create]
  resources :performers, except: [:new, :create] do
    resources :events, only: [:index]
  end
  resources :venues do
    resources :events, only: [:index]
  end
  resources :events
  resources :transactions
  resources :transaction_sources, except: [:new, :create, :show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]


end

app/views/partials/_flash_messages.html.erb
<div id="flash-container" %>
	<% if !flash.empty? %>
		<% flash.each do |key, value| %>
			<p id="flash-title"><%= key.capitalize %>:</p>
			<ul>
	    	<li class="flash-message"><%= value %></li>
	    </ul>
	  <% end %>
	<% end %>
</div>

app/views/partials/_header_menu.html.erb
<% if logged_in? %>
	<!-- <p id="header-login"><%= link_to 'Logout', logout_path, method: :delete %></p> -->
	<div class="dropdown">
  	<button onclick="showDropdown()" class="dropbtn clearfix"><%= image_tag "new-menu-icon.png", id: "menu-image" %></button>
	  <div id="myDropdown" class="dropdown-content">
	    <%= link_to render(partial: 'partials/menu_item', locals: {text: "Events"}), events_path %>
	    <%= link_to render(partial: 'partials/menu_item', locals: {text: "Performers"}), performers_path %>
	    <%= link_to render(partial: 'partials/menu_item', locals: {text: "Venues"}), venues_path %>
	    <% if current_user.admin? %>
		    <%= link_to render(partial: 'partials/menu_item', locals: {text: "Transaction Sources"}), transaction_sources_path %>
		    <%= link_to render(partial: 'partials/menu_item', locals: {text: "Users"}), users_path %>
	    <% end %>
	    <%= link_to render(partial: 'partials/menu_item', locals: {text: "Settings"}), edit_user_path(current_user) %>
	    <%= link_to render(partial: 'partials/menu_item', locals: {text: "Log Out"}), logout_path, method: :delete %>
	  </div>
	</div>
<% else %>
	<div class="dropdown">
  	<button onclick="showDropdown()" class="dropbtn clearfix"><%= image_tag "new-menu-icon.png", id: "menu-image" %></button>
	  <div id="myDropdown" class="dropdown-content">
	  	<%= link_to render(partial: 'partials/menu_item', locals: {text: "About"}), about_path %>
	    <%= link_to render(partial: 'partials/menu_item', locals: {text: "Contact"}), contact_page_path %>
	    <%= link_to render(partial: 'partials/menu_item', locals: {text: "Log In"}), login_path %>
	    <%= link_to render(partial: 'partials/menu_item', locals: {text: "Sign Up"}), new_user_path %>
	  </div>
	</div>
<% end %>

app/views/partials/_menu_item.html.erb
<div class="menu-item"><%= text %></div>