config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#home'
  get 'about', to: 'application#about'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#fb_create'
  
  get 'contact', to: 'contacts#new', as: 'contact_page'
  get 'most-active-user', to: 'users#most_active_user'

  resources :users do
    get :admins, on: :collection
  	resources :transactions
    resources :events, only: [:index, :show] do
      resources :transactions, only: [:index]
    end
  end
  resources :contacts, only: [:new, :create]
  resources :performers, except: [:new, :create] do
    resources :events, only: [:index]
  end
  resources :venues do
    resources :events, only: [:index]
  end
  resources :events
  resources :transactions
  resources :transaction_sources, except: [:new, :create, :show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]


end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password(validations: false)

	has_many :transactions, dependent: :destroy
	has_many :events, through: :transactions

	validates :name, :email, presence: true
	validates :email, uniqueness: true
	validate :password_min_length_if_present
	validates_confirmation_of :password, unless: :facebook_user?
	validates_presence_of :password, on: :create, unless:
:facebook_user?


	before_create :create_activation_digest, :downcase_email

	scope :admins, -> { where(admin: true) }
	scope :most_active_user, -> { joins(:transactions).group(:id).order('COUNT(transactions.id) DESC').first }

	attr_accessor :remember_token, :activation_token, :reset_token

	def self.new_token
    SecureRandom.urlsafe_base64
	end	

	def self.exists(id)
		self.find_by(id: id)
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, remember_token.digest)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(attribute, token)
		digest = self.send("#{attribute}_digest")
		if digest.nil?
			false
		else
			BCrypt::Password.new(digest).is_password?(token)
		end
	end

	def purchases
		
	end

	def sales

	end

	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	def activate
		self.update_attributes(activated: true, activated_at: Time.now)
	end

	def create_reset_digest
		self.reset_token = User.new_token
		update_attribute(:reset_digest, reset_token.digest)
		update_attribute(:reset_sent_at, Time.zone.now)
 
	end

	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end

	def first_name
		name.split(" ").first
	end

	def tickets_purchased
		count = 0
		events.uniq.each{|e| count += e.tickets_purchased(self)}
		count
	end

	def tickets_sold
		count = 0
		events.uniq.each{|e| count += e.tickets_sold(self)}
		count
	end

	def total_purchase
		sum = 0
		events.uniq.each{|e| sum += e.total_purchase(self)}
		sum
	end

	def total_sale
		sum = 0
		events.uniq.each{|e| sum += e.total_sale(self)}
		sum
	end

	def liquid_profit
		(total_sale - total_purchase).round(2)
	end

	def actual_inventory_value
		sum = 0
		events.uniq.each{|e| sum += e.actual_inventory_value(self)}
		sum
	end

	def projected_inventory_value
		sum = 0
		events.uniq.each{|e| sum += e.projected_inventory_value(self)}
		sum
	end

	def projected_profit
		liquid_profit + projected_inventory_value
	end

	def number_of_transactions
		transactions.count
	end

	def inventory_count
		count = 0
		events.uniq.each{|e| count += e.tickets_remaining(self)}
		count
	end

	def facebook_user?
		!self.facebook_id.nil?
	end

	private

	def password_min_length_if_present
		if !password.nil? && password.length < 6
			errors.add(:password, "is too short (minimum is 6 characters)")
		end
	end

	def create_activation_digest
		self.activation_token = User.new_token
		self.activation_digest = activation_token.digest
	end

	def downcase_email
		email.downcase!
	end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2 class="form-title" ><%= form_name %></h2>

  <div class="form-section">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-section">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="form-section">
    <%= f.label :birthdate %>
    <%= f.date_field :birthdate %>
  </div>
  <div class="form-section">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="form-section">
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="submit">
    <%= f.submit button_text %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li id="venue-listing" class="clearfix">
	<div class="listing-left" id="venue-left">
		<div id="venue-name"><%= user.name %></div>
	</div>
	<div class="listing-right" id="venue-right">
		<div id="event-venue"><%= user.email %></div>
	</div>
</li>

app/views/users/edit.html.erb
<div class="form-container">
	<%= render 'form', form_name: "Settings", button_text: "Save" %>
</div>

app/views/users/index.html.erb
<div class="index-container">
  <div id="index-wrapper" class="wrapper clearfix">
    <%= render "partials/flash_messages" %>
    <h2>Users</h2>
    <ol>
      <% @users.each do |user| %>
        <%= link_to render(partial: 'users/user', locals: {user: user}), user %>
      <% end %>
    </ol>
    <%= will_paginate %>
  </div>

  <br>

  <p class="create-new-link"><%= link_to 'Back To Home', root_path %></p>
</div>

app/views/users/most_active_user.html.erb
<h2><%= @user.name %></h2>

app/views/users/new.html.erb
<div class="form-container">
	<%= render 'form', form_name: "Sign Up", button_text: "Submit" %>
	<div class="fb-login-button">
    <%= link_to(image_tag("https://pngimage.net/wp-content/uploads/2018/06/login-with-facebook-button-png-transparent-2.png"), '/auth/facebook') %>
  </div>
</div>

app/views/users/show.html.erb
<div class="show-container" id="user-info-container">
	<%= render "partials/flash_messages" %>
	<div id="user-info">
		<h2 id="welcome-message">Welcome back, <%= @user.first_name %>!</h2>
		<p><%= @user.name %></p>
		<p><%= @user.email %></p>
		<div class="ud-links" id="user-ud-links">
			<%= link_to "edit", edit_user_path(@user) %> | <%= link_to 'delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %> 
		</div>
		<div id="profits-container">
			<p><%= @user.tickets_sold %> tickets sold for a total revenue of <%= @user.total_sale.price %></p>
			<p><%= @user.tickets_purchased %> tickets purchased for a total of <%= @user.total_purchase.price %></p>
			<p>Inventory Count: <%= @user.inventory_count %></p>
			<p>Inventory Value: <%= @user.actual_inventory_value.price %> original | <%= @user.projected_inventory_value.price %> projected</p>
			<p><%= @user.inventory_count == 0 ? "Total" : "Pojected" %> Profit: <%= @user.projected_profit.price %></p>
		</div>
	</div>
</div>

<div id="user-lists" class="clearfix">
	<div id="events-wrapper" class="wrapper clearfix">
		<div id="upcoming-events" class="show-container">
			<h3>Upcoming Events</h3>
			<ol>
				<% @upcoming_events.each do |event| %>
					<%= link_to render(partial: 'events/event', locals: {event: event}), user_event_path(@user, event) %>
				<% end %>
			</ol>
		</div>
		<div class="user-list-links">
			<div id="all-events-link"><%= link_to "All My Events", user_events_path(@user) %></div>
			<div id="new-event-link"><%= link_to "New Event", new_event_path %></div>
		</div>
	</div>
	<div id="transactions-wrapper" class="wrapper clearfix">
		<div id="recent-transactions" class="show-container">
			<h3>Recent Transactions</h3>
			<ol>
				<% @recent_transactions.each do |transaction| %>
					<%= link_to render(partial: 'transactions/transaction', locals: {transaction: transaction}), user_transaction_path(@user, transaction) %>
				<% end %>
			</ol>
		</div>
		<div class="user-list-links">
			<div id="all-transactions-link"><%= link_to "All My Transactions", user_transactions_path(@user) %></div>
			<div id="new-transaction-link"><%= link_to "New Transaction", new_user_transaction_path(@user) %></div>
		</div>
	</div>
</div>