config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#home'
  get 'about', to: 'application#about'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#fb_create'
  
  get 'contact', to: 'contacts#new', as: 'contact_page'
  get 'most-active-user', to: 'users#most_active_user'

  resources :users do
    get :admins, on: :collection
  	resources :transactions
    resources :events, only: [:index, :show] do
      resources :transactions, only: [:index]
    end
  end
  resources :contacts, only: [:new, :create]
  resources :performers, except: [:new, :create] do
    resources :events, only: [:index]
  end
  resources :venues do
    resources :events, only: [:index]
  end
  resources :events
  resources :transactions
  resources :transaction_sources, except: [:new, :create, :show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]


end

app/models/event.rb
class Event < ApplicationRecord

	belongs_to :venue
	belongs_to :performer
	has_many :transactions, dependent: :destroy

	validates :date, presence: true

	scope :upcoming, -> { where("date >= ?", Date.today) }
	scope :past, -> { where("date < ?", Date.today) }

	def name
		"#{performer.name} @ #{venue.name} (#{formatted_date})"
	end

	def location
		venue.location
	end

	def sales(user)
		user.transactions.where(["event_id = ? and direction = ?", self.id, "Sale"])
	end

	def purchases(user)
		user.transactions.where(["event_id = ? and direction = ?", self.id, "Purchase"])
	end

	def total_purchase(user)
		sum = 0
		purchases(user).each{ |t| sum += t.amount}
		sum
	end

	def total_sale(user)
		sum = 0
		sales(user).each{ |t| sum += t.amount}
		sum
	end

	def average_purchase_price(user)
		tickets_purchased(user) == 0 ? 0 : (total_purchase(user)/tickets_purchased(user)).round(2)
	end

	def average_sale_price(user)
		tickets_sold(user) == 0 ? 0 : (total_sale(user)/tickets_sold(user)).round(2)
	end

	def tickets_purchased(user)
		sum = 0
		purchases(user).each{|t| sum += t.quantity}
		sum
	end

	def tickets_sold(user)
		sum = 0
		sales(user).each{|t| sum += t.quantity}
		sum
	end

	def tickets_remaining(user)
		tickets_purchased(user) - self.tickets_sold(user)
	end

	def actual_inventory_value(user)
		(average_purchase_price(user) * tickets_remaining(user)).round(2)
	end

	def projected_inventory_value(user)
		tickets_sold(user) > 0 ? (average_sale_price(user) * tickets_remaining(user)).round(2) : actual_inventory_value(user)
	end

	def liquid_profit(user)
		(total_sale(user) - total_purchase(user)).round(2)
	end

	def projected_profit(user)
		(liquid_profit(user) + projected_inventory_value(user)).round(2)
	end

	def complete?(user)
		tickets_remaining(user) <= 0
	end

	def complete_string(user)
		tickets_remaining = tickets_remaining(user)
		complete?(user) ? "COMPLETE" : "INCOMPLETE (#{tickets_remaining} #{'ticket'.pluralize(tickets_remaining)} remaining)"
	end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_admin_event.html.erb
<li id="event-listing" class="clearfix">
	<div class="listing-left" id="admin-event-left">
		<div id="event-artist"><%= event.performer.name %></div>
	</div>
	<div class="listing-right" id="admin-event-right">
		<div id="event-venue"><%= event.venue.name %></div>
		<div id="event-date"><%= event.formatted_date(:long) %></div>
	</div>
	<div id="index-ud-links">
		<div id="event-edit" class="edit-link"><%= link_to 'edit', edit_event_path(event) %></div>
		<div id="event-delete" class="delete-link"><%= link_to 'delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></div>
	</div>
</li>

app/views/events/_event.html.erb
<li id="event-listing" class="clearfix">
	<div class="listing-left">
		<div id="event-artist"><%= event.performer.name %></div>
	</div>
	<div class="listing-right">
		<div id="event-venue"><%= event.venue.name %></div>
		<div id="event-date"><%= event.formatted_date(:long) %></div>
	</div>
</li>

app/views/events/_form.html.erb
<div class="form-container">
  <%= form_for @event do |f| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
        <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <h2 class="form-title" id="event-form-title"><%= form_name %></h2>

    <div class="form-section">
      <%= f.label :performer_id, "Performer" %>
      <%= f.select :performer_id, options_for_select(@performers, @performer_id) %>
    </div>

    <div class="form-section">
      <%= label_tag :new_performer, "or Add Performer" %>
      <%= text_field_tag :new_performer %>
    </div>

    <div class="form-section">
      <%= f.label :venue_id, "Venue" %>
      <%= f.select :venue_id, options_for_select(@venues, @venue_id), { include_blank: 'Select Venue' } %>
      <div class="not-listed-link">
        <%= link_to "Venue not listed", new_venue_path %>
      </div>
    </div>

    <div class="form-section">
      <%= f.label :date %>
      <%= f.date_field :date %>
    </div>

    <div class="submit" id="event-form-submit">
      <%= f.submit button_text %>
    </div>

  <% end %> 
</div>

app/views/events/edit.html.erb
<%= render 'form', form_name: "Edit Event", button_text: "Save" %>

app/views/events/index.html.erb
<div class="index-container">
  <div id="index-wrapper" class="wrapper clearfix">
    <%= render "partials/flash_messages" %>
    <h2><%= @title %></h2>
    <div class="sort-selectors">
      <%= form_tag(@current_path, method: :get) do %>
        Sort: 
        <%= select_tag(:sort_by, options_for_select(["Date", "Performer Name", "Venue Name"], params[:sort_by])) %>
        <%= select_tag(:order_by, options_for_select(["ASC","DESC"], params[:order_by])) %>
        <%= select_tag(:range, options_for_select(["All Events", "Past Events", "Upcoming Events"], params[:range])) %>
        <%= submit_tag "Submit" %>
      <% end %>
    </div>
    <ol>
      <% @events.each do |event| %>
        <% if @user %>
          <%= link_to render(partial: 'events/event', locals: {event: event}), user_event_path(@user, event) %>
        <% elsif current_user.admin? %>
          <%= render(partial: 'events/admin_event', locals: {event: event}) %>
        <% else %>
          <%= render(partial: 'events/event', locals: {event: event}) %>
        <% end %>
      <% end %>
    </ol>
    <%= will_paginate %>
  </div>

  <br>

  <p class="create-new-link"><%= link_to 'New Event', new_event_path %></p>
</div>

app/views/events/new.html.erb
<%= render 'form', form_name: "Create Event", button_text: "Submit" %>

app/views/events/show.html.erb
<div class="show-container resource-show-container clearfix" id="event-show-container">
	<h2>Event Details</h2>
	<div class="resource-details" id="event-details">
		<p id="event-performer">Performer: <%= link_to @event.performer.name, @event.performer %></p>
		<p id="event-venue">Venue: <%= link_to @event.venue.name, @event.venue %></p>
		<p id="event-location">Location: <%= @event.location %></p>
		<p id="event-date">Date: <%= @event.formatted_date(:long) %></p>
		
		<div id="event-show-border"></div>
		<div id="event-ticket-info">
			<p id="event-complete"><%= @event.complete_string(@user) %></p>
			
			<p><%= "#{@event.tickets_purchased(@user)} tickets purchased for a total of #{@event.total_purchase(@user).price} (#{@event.average_purchase_price(@user).price} each)" %></p>

			<p><%= "#{@event.tickets_sold(@user)} tickets sold for a total of #{@event.total_sale(@user).price} (#{@event.average_sale_price(@user).price} each)" %></p>

			<% if @event.complete?(@user) %>
				<p>Total Profit: <%= @event.liquid_profit(@user).price %></p>
			<% else %>
				<p>Inventory Value: <%= @event.actual_inventory_value(@user).price %> original | <%= @event.projected_inventory_value(@user).price %> projected</p>
				<p>Projected Profit: <%= @event.projected_profit(@user).price %></p>
			<% end %>
			
		</div>
	</div>

	<div id="transactions-wrapper" class="wrapper clearfix">
		<div id="recent-transactions" class="show-container">
			<h3>Recent Transactions</h3>
			<ol>
				<% @recent_transactions.each do |transaction| %>
					<%= link_to render(partial: 'transactions/transaction', locals: {transaction: transaction}), user_transaction_path(@user, transaction) %>
				<% end %>
			</ol>
		</div>
		<div id="all-transactions-link"><%= link_to "All Event Transactions", user_event_transactions_path(@user, @event) %></div>
	</div>
</div>