config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#home'
  get 'about', to: 'application#about'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#fb_create'
  
  get 'contact', to: 'contacts#new', as: 'contact_page'
  get 'most-active-user', to: 'users#most_active_user'

  resources :users do
    get :admins, on: :collection
  	resources :transactions
    resources :events, only: [:index, :show] do
      resources :transactions, only: [:index]
    end
  end
  resources :contacts, only: [:new, :create]
  resources :performers, except: [:new, :create] do
    resources :events, only: [:index]
  end
  resources :venues do
    resources :events, only: [:index]
  end
  resources :events
  resources :transactions
  resources :transaction_sources, except: [:new, :create, :show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]


end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<div class="form-container">
  <%= form_for @transaction do |f| %>
    <% if @transaction.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h3>
        <ul>
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <h2 class="form-title" id="event-form-title"><%= form_name %></h2>

    <!-- User (invisible) -->
    <%= hidden_field_tag :user_id, @user.id %>

    <!-- Event -->
    <div class="form-section">
      <%= f.label :event_id, "Event" %>
      <%= f.select :event_id, options_for_select(@events, @event_id), { include_blank: 'Select Event' } %>
      <div class="not-listed-link">
        <%= link_to "Event not listed", new_event_path %>
      </div>
    </div>

    <!-- Price -->
    <div class="form-section">
      <%= f.label :amount, 'Price (USD)' %>
      <%= f.number_field :amount, step: '0.01', value: (f.object.amount.nil? ? nil : ('%.2f' % f.object.amount)) %>
    </div>

    <!-- Direction -->
    <div class="form-section">
      <div id="purchase-button-container">
        <%= f.radio_button :direction, "Purchase", id: "purchase-button" %>
        <%= f.label :direction, "Purchase", value: "Purchase", id: "purchase-label", for: "purchase-button" %>
      </div>
      <div id="sale-button-container">
        <%= f.radio_button :direction, "Sale", id: "sale-button" %>
        <%= f.label :direction, "Sale", value: "Sale", id: "sale-label", for: "sale-button" %>
      </div>
    </div>

    <!-- Quantity -->
    <div class="form-section">
      <%= f.label :quantity %>
      <%= f.number_field :quantity %>
    </div>

    <!-- Source -->
    <div class="form-section">
      <%= f.label :transaction_source_id, "Source" %>
      <%= f.select :transaction_source_id, options_for_select(@sources, @transaction.transaction_source_id) %>
    </div>    

    <div class="form-section">
      <%= label_tag :new_source, "or Add Source" %>
      <%= text_field_tag :new_source %>
    </div>

    <!-- Order Number -->
    <div class="form-section">
      <%= f.label :order_number, "Order Number" %>
      <%= f.text_field :order_number %>
    </div>

    <!-- Date -->
    <div class="form-section">
      <%= f.label :date, "Order Date" %>
      <%= f.date_field :date %>
    </div>

    <!-- Notes -->  
    <div class="form-section">
      <%= f.label :notes %>
      <%= f.text_area :notes %>
    </div> 

    <div class="submit" id="event-form-submit">
      <%= f.submit button_text %>
    </div> 

  <% end %>
</div>

app/views/transactions/_transaction.html.erb
<li id="transaction-listing" class="clearfix">
	<div class="listing-left">
		<div id="order-number"><%= transaction.order_number %></div>
		<div id="date"><%= transaction.formatted_date(:long) %></div>
	</div>

		
	<div class="listing-right">
		<div id="transaction-event"><%= transaction.event.name %></div>
	</div>
</li>

app/views/transactions/edit.html.erb
<%= render 'form', form_name: "Edit Transaction", button_text: "Save" %>

app/views/transactions/index.html.erb
<div class="index-container">
  <div id="index-wrapper" class="wrapper clearfix">
    <%= render "partials/flash_messages" %>
    <div id="transaction-index-title">
      <h2>My Transactions</h2>
      <p><%= @subtitle if @subtitle %></p>
    </div>
    <div class="sort-selectors">
      <%= form_tag(@current_path, method: :get) do %>
        Sort: 
        <%= select_tag(:order_by, options_for_select([["Newest First", "DESC"], ["Oldest First", "ASC"]], params[:order_by])) %>
        <%= select_tag(:filter_by, options_for_select(["All Transactions", "Purchases", "Sales"], params[:filter_by])) %>
        <%= submit_tag "Submit" %>
      <% end %>
    </div>
    <ol>
      <% @transactions.each do |transaction| %>
        <%= link_to render(partial: 'transactions/transaction', locals: {transaction: transaction}), user_transaction_path(@user, transaction) %>
      <% end %>
    </ol>
    <%= will_paginate %>
  </div>

  <br>

  <p class="create-new-link"><%= link_to 'New Transaction', new_user_transaction_path(@user) %></p>
</div>

app/views/transactions/new.html.erb
<%= render 'form', form_name: "Add Transaction", button_text: "Submit" %>

app/views/transactions/show.html.erb
<div class="show-container resource-show-container" id="transaction-show-container">
	<%= render "partials/flash_messages" %>
	<div id="transaction-show-header">
		<h2>Transaction <%= @transaction.order_number %></h2>
		<div id="transaction-direction"><%= @transaction.direction %></div>
		<div class="ud-links" id="transaction-ud-links">
			<%= link_to "edit", edit_user_transaction_path(@user, @transaction) %> | <%= link_to 'delete', user_transaction_path(@user, @transaction), method: :delete, data: { confirm: 'Are you sure?' } %>
		</div>
	</div>
	<div class="resource-details" id="transaction-details">
		<div class="clearfix" id="transaction-event">
			<p class="title">Event: </p>
			<p class="attribute"><%= link_to @transaction.event.name, user_event_path(@user, @transaction.event) %></p>
		</div>
		<div class="clearfix" id="transaction-price">
			<p class="title">Price: </p>
			<p class="attribute"><%= @transaction.price %></p>
		</div>
		<div class="clearfix" id="transaction-quantity">
			<p class="title">Quantity: </p>
			<p class="attribute"><%= @transaction.quantity %></p>
		</div>
		<div class="clearfix" id="transaction-source">
			<p class="title">Source: </p>
			<p class="attribute"><%= @transaction.transaction_source.name %></p>
		</div>
		<div class="clearfix" id="transaction-date">
			<p class="title">Order Date: </p>
			<p class="attribute"><%= @transaction.formatted_date(:long) %></p>
		</div>
		<div class="clearfix" id="transaction-date">
			<p class="title">Order Number: </p>
			<p class="attribute"><%= @transaction.order_number %></p>
		</div>
		<div class="clearfix" id="transaction-notes">
			<p class="title">Notes: </p>
			<p class="attribute"><%= @notes %></p>
		</div>
	</div>
</div>